language: php

php:
  - 5.5
  - 5.6

env:
  matrix:
    - TYPO3_VERSION=7.6.0
    - TYPO3_VERSION=dev-master

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  slack:
    secure: Cg6TncMmzvnRADbTNds/zHA1UEs1CaPXJKoZpEtGmnbPSaA+Jgtj9CDqhzjdaGK7t3nSomR4oCmHkrYK4c4sLvC1GjmvtydJ6j2doE72VQrRI2B47vcfhVOJwnGvkALFsVjSONp3ENCuP8pORw8A5b1+i9bFIcr7IsmuRPUyHak=

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms=$TYPO3_VERSION
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit --colors  -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/

  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

  - >
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --colors  -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/FunctionalTests.xml {}'
